default_platform(:ios)

platform :ios do

	desc "Run all unit tests"
	lane :run_unit_tests do 
		run_tests(
			workspace: ENV["WORKSPACE"],
	        device: ENV["DEVICE"],
			scheme: ENV["UT_SCHEME"],
			derived_data_path: ENV["DERIVED_DATA_PATH"]
			)
	end

	desc "Run all UI tests" 
	lane :run_ui_tests do 
		run_tests(
			workspace: ENV["WORKSPACE"],
			device: ENV["DEVICE"],
			scheme: ENV["UIT_SCHEME"],
			derived_data_path: ENV["DERIVED_DATA_PATH"]
			)
	end

	desc "Read and install development code signing certificates and provisioning profiles"
	lane :fetch_development_code_signing do
		match(
	  		type:"development",
	  		readonly: true,
	  		generate_apple_certs: false
	  	)
	  	update_code_signing_settings(
	  		code_sign_identity: "iPhone Development",
	  		profile_name: ""
	  		)
		update_project_team
	end

	desc "Read and install production code signing certificates and provisioning profiles"
	lane :fetch_production_code_signing do
		match(
	  		type:"appstore", 
	  		readonly: true,
	  		generate_apple_certs: false
	  	)
	  	update_code_signing_settings(
	  		code_sign_identity: "iPhone Distribution", 
	  		profile_name: ENV["PRODUCTION_PROFILE_NAME"]
	  		)
		update_project_team
	end

	desc "Distribute Testflight build"
	lane :beta do

		run_unit_tests
		run_ui_tests

		fetch_production_code_signing
		increment_build_number
		build_app
		# app_store_connect_api_key
		# upload_to_testflight(skip_submission: true, skip_waiting_for_build_processing: true)
		clean_build_artifacts
	end

end