default_platform(:ios)

platform :ios do

	desc "Run all unit tests"
	lane :run_unit_tests do 
		run_tests(
			workspace: ENV["WORKSPACE"],
			device: ENV["DEVICE"],
			scheme: ENV["UT_SCHEME"],
			derived_data_path: ENV["DERIVED_DATA_PATH"]
		)
	end

	desc "Run all UI tests" 
	lane :run_ui_tests do 
		run_tests(
			workspace: ENV["WORKSPACE"],
			device: ENV["DEVICE"],
			scheme: ENV["UIT_SCHEME"],
			derived_data_path: ENV["DERIVED_DATA_PATH"]
		)
	end

	desc "Read and install development code signing certificates and provisioning profiles"
	lane :fetch_development_code_signing do
		app_identifier = ENV["APP_IDENTIFIER"]

		sync_code_signing(
	  		type: "development",
	  		readonly: true,
	  		generate_apple_certs: false
	  	)
	  	update_code_signing_settings(
	  		targets: ["MinderaPeople"],
	  		code_sign_identity: "iPhone Development",
	  		profile_name: ENV['sigh_' + app_identifier + '__profile-name'],
	  		build_configurations: ["Debug"]
	  	)
		update_project_team(
			targets: ["MinderaPeople"]
		)
	end

	desc "Read and install production code signing certificates and provisioning profiles"
	lane :fetch_production_code_signing do
		app_identifier = ENV["APP_IDENTIFIER"]

		sync_code_signing(
			type: "appstore", 
	  		readonly: true,
	  		generate_apple_certs: false
	  	)
	  	update_code_signing_settings(
	  		targets: ["MinderaPeople"],
	  		code_sign_identity: "iPhone Distribution", 
	  		profile_name: ENV['sigh_' + app_identifier + '_appstore_profile-name'],
	  		build_configurations: ["Release"]
	  	)
		update_project_team(
			targets: ["MinderaPeople"]
		)
	end

	lane :fetch_and_increment_build_number do
		current_version = get_version_number
		latest_build_number = latest_testflight_build_number(
			api_key: ENV["APP_STORE_CONNECT_API_KEY"],
			version: current_version,
			app_identifier: ENV["APP_IDENTIFIER"]
		)
		increment_build_number(
			build_number: (latest_build_number + 1)
		)
	end

	desc "Distribute Testflight build"
	lane :beta do

		run_unit_tests
		run_ui_tests

		fetch_production_code_signing

		app_store_connect_api_key(
			key_id: ENV["ASC_KEY_ID"],
			issuer_id: ENV["ASC_ISSUER_ID"],
			key_content: ENV["APP_STORE_CONNECT_API_KEY"],
			is_key_content_base64: true,
			in_house: false
		)

		fetch_and_increment_build_number

		build_app(
			configuration: "Release",
			export_options: {
				method: "ad-hoc",
				uploadBitcode: false
			}
		)

		upload_to_testflight(
			skip_submission: true,
			skip_waiting_for_build_processing: true
		)

		clean_build_artifacts
	end

end
