default_platform(:ios)

platform :ios do

    desc "Run all unit tests"
    lane :run_unit_tests do 
        run_tests(
            workspace: ENV["WORKSPACE"],
            device: ENV["DEVICE"],
            scheme: ENV["UT_SCHEME"],
            derived_data_path: ENV["DERIVED_DATA_PATH"]
        )
    end

    desc "Run all UI tests" 
    lane :run_ui_tests do 
        run_tests(
            workspace: ENV["WORKSPACE"],
            device: ENV["DEVICE"],
            scheme: ENV["UIT_SCHEME"],
            derived_data_path: ENV["DERIVED_DATA_PATH"]
        )
    end

    desc "Distribute Testflight build"
    lane :beta do
        app_store_connect_api_key(
            is_key_content_base64: true,
            in_house: false
        )

        fetch_production_code_signing
        fetch_and_increment_build_number

        build_app(
            configuration: "Release",
            export_method: "app-store",
            export_options: {
                provisioningProfiles: {
                    ENV["FL_APP_IDENTIFIER"] => ENV['sigh_' + app_identifier + '_appstore_profile-name']
                },
                uploadBitcode: false
            }
        )

        upload_to_testflight(
            api_key: lane_context[SharedValues::APP_STORE_CONNECT_API_KEY],
            skip_submission: true,
            skip_waiting_for_build_processing: true
        )

        clean_build_artifacts
    end
end

def fetch_and_increment_build_number 
    current_version = get_version_number
    latest_build_number = latest_testflight_build_number(
        api_key: lane_context[SharedValues::APP_STORE_CONNECT_API_KEY],
        version: current_version
    )
    increment_build_number(
        build_number: (latest_build_number + 1)
    )
end

def fetch_production_code_signing 
    app_identifier = ENV["FL_APP_IDENTIFIER"]

    sync_code_signing(
        api_key: lane_context[SharedValues::APP_STORE_CONNECT_API_KEY],
        type: "appstore",
        readonly: true,
        generate_apple_certs: false
    )

    update_code_signing_settings(
        use_automatic_signing: false,
        code_sign_identity: "iPhone Distribution", 
        profile_name: ENV['sigh_' + app_identifier + '_appstore_profile-name'],
        build_configurations: ["Release"]
    )

    update_project_provisioning(
        code_signing_identity: "iPhone Distribution",
        profile: ENV['sigh_' + app_identifier + '_appstore_profile-path'],
        build_configuration: "Release"
    )

    update_project_team
end
